version: "3"

services:

  runtime-setup:
    image: netty:centos-6-1.8
    build:
      args:
        java_version : "graalvm-ce-java8@20.1.0"

  build:
    image: netty:centos-6-1.8

  build-leak:
    image: netty:centos-6-1.8

  build-boringssl-static:
    image: netty:centos-6-1.8

  build-leak-boringssl-static:
    image: netty:centos-6-1.8

  shell:
    image: netty:centos-6-1.8
